language: scala
before_script:
  - npm install
  - npm install -g gulp
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION plugin-test
  - gulp
