language: scala
before_script:
  - npm install
  - npm install -g gulp
  - mv -f conf/application-logger.test.xml conf/application-logger.xml
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle | grep ERROR
  - sbt ++$TRAVIS_SCALA_VERSION test | grep ERROR
  - sbt ++$TRAVIS_SCALA_VERSION plugin-test | grep ERROR
  - gulp
